In [3]:
import numpy as np

In [2]:
np.ceil(np.sin(np.deg2rad(30)))

1.0

- ceil round for the big

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.full((3,2),1)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [5]:
np.random.random((3,3))

array([[0.1794235 , 0.05977743, 0.39639671],
       [0.7431077 , 0.12893926, 0.31971514],
       [0.29418996, 0.15583969, 0.21760745]])

In [6]:
c = np.random.randint(0,10,(3,3))
c

array([[5, 3, 2],
       [9, 6, 8],
       [3, 1, 4]])

In [7]:
c[1,2]

8

In [8]:
c[0,:]

array([5, 3, 2])

In [5]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.eye(3 , dtype = 'int32') # identity matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
np.diag([1,2,3]) # diagonal matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

<hr>

In [13]:
e = [1,2,3,4,5,6,7,8,9]
np.random.shuffle(e)
e

[2, 4, 8, 9, 7, 3, 6, 5, 1]

In [14]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [15]:
np.any(c>8)

True

In [16]:
np.all(c>8)

False

In [17]:
np.trace(c) # sum of diagonal

15

In [18]:
np.linalg.det(c) # the determainant of the matrix

26.000000000000014

In [19]:
np.linalg.eig(c) # the adjoient of matrix

(array([12.53235824+0.j        ,  1.23382088+0.74317934j,
         1.23382088-0.74317934j]),
 array([[ 0.41462258+0.j        ,  0.63389766+0.j        ,
          0.63389766-0.j        ],
        [ 0.87543886+0.j        , -0.49941536+0.31180669j,
         -0.49941536-0.31180669j],
        [ 0.24838462+0.j        , -0.44456302-0.23216022j,
         -0.44456302+0.23216022j]]))

-  The inverse = adjoient / determainant

<hr>

In [20]:
len(c) # numbers of rows

3

In [21]:
np.size(c) # numbres of the elements

9

In [25]:
c.ndim # dimention of matrix

2

In [26]:
c.shape

(3, 3)

In [27]:
c.dtype

dtype('int32')

In [24]:
d = np.arange(1,11)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
D = d.reshape(-1,1)
D

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [8]:
Z = np.c_[D,D**2,D**3] # connection
Z

array([[   1,    1,    1],
       [   2,    4,    8],
       [   3,    9,   27],
       [   4,   16,   64],
       [   5,   25,  125],
       [   6,   36,  216],
       [   7,   49,  343],
       [   8,   64,  512],
       [   9,   81,  729],
       [  10,  100, 1000]])

In [4]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]

array([[1, 2, 3, 0, 0, 4, 5, 6]])

In [13]:
np.ptp(Z,axis=0)

array([  9,  99, 999])

In [29]:
np.add.accumulate(d) # cumulative

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [30]:
np.multiply.accumulate(d) # factorial of cumulative

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

<hr>

In [7]:
f = np.arange(4).reshape(2,2)
f

array([[0, 1],
       [2, 3]])

In [8]:
g = f*2
g

array([[0, 2],
       [4, 6]])

In [9]:
np.vstack((f,g))

array([[0, 1],
       [2, 3],
       [0, 2],
       [4, 6]])

In [10]:
np.hstack((f,g))

array([[0, 1, 0, 2],
       [2, 3, 4, 6]])

In [11]:
np.max(f)

3

In [36]:
np.argmin(f)

0

In [37]:
f*g   # Every number in the corresponding to him

array([[ 0,  2],
       [ 8, 18]])

In [12]:
np.dot(f,g)

array([[ 4,  6],
       [12, 22]])

# be careful when coping arrays!!!!

In [39]:
a = np.array([1,2,3])
b = a
b[0] = 100
a
# the correct >>> b = a.copy()

array([100,   2,   3])

#              polynomial

In [40]:
poly = np.polynomial.Polynomial
x = np.array([0,20,40,60,80,100,120,140])
y =np.array([10,9,8,7,6,5,4,3])
equation = poly.fit(x,y,1,full=True)
equation

(Polynomial([ 6.5, -3.5], domain=[  0., 140.], window=[-1.,  1.]),
 [array([6.7394794e-30]), 2, array([1., 1.]), 1.7763568394002505e-15])

In [41]:
a = np.poly1d((1,2,3)) # make a equation >>> x2+2x+3
a

poly1d([1, 2, 3])

In [42]:
np.polyder(a) # derivative of equ(a) >> 2x+2

poly1d([2, 2])

In [43]:
np.polyint(a)# intgration

poly1d([0.33333333, 1.        , 3.        , 0.        ])

In [44]:
np.roots(a) # The roots of equ

array([-1.+1.41421356j, -1.-1.41421356j])

In [53]:
a(5)

38

## The End