# import torch

In [1]:
import torch 

# Make torch tensors

In [2]:
x = torch.randn(3,3)
x

tensor([[ 0.3795, -0.2128,  0.4384],
        [-0.3576, -1.0092,  0.2302],
        [-1.4584,  0.8828,  0.8090]])

In [16]:
x.flatten()

tensor([ 0.3795, -0.2128,  0.4384, -0.3576, -1.0092,  0.2302, -1.4584,  0.8828,
         0.8090])

In [4]:
tensor1 = torch.tensor([1,2,3])
tensor1

tensor([1, 2, 3])

In [5]:
type(tensor1)

torch.Tensor

# torch grads 

In [6]:
w = torch.tensor([1.,2.,3.] ,requires_grad=True) # the numbers in tensor with grad  should be float 
z = w *2
l = z.sum()
l.backward()
w

tensor([1., 2., 3.], requires_grad=True)

In [7]:
w.grad

tensor([2., 2., 2.])

In [8]:
l.grad_fn

In [9]:
l.grad_fn.next_functions[0][0]

In [10]:
w.requires_grad_(False) 

tensor([1., 2., 3.])

In [17]:
l.backward() # we should use requires_grad=True

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [19]:
w = torch.tensor([1.,2.,3.] ,requires_grad=True)
w.detach()

tensor([1., 2., 3.])

In [20]:
w

tensor([1., 2., 3.], requires_grad=True)

In [21]:
w.detach_() # like requires_grad_(False) make overwriting 

tensor([1., 2., 3.])

In [22]:
w

tensor([1., 2., 3.])

when we write _ in any function it make overwriting like implace = True in pandas 

# torch backpropagation 

i will make a small linear regression model 

In [23]:
x= torch.tensor(1.)
y= torch.tensor(2.)
w = torch.tensor(1. , requires_grad=True)

for _ in range(500) :
    
    ypred = w * x
    loss = (ypred-y)**2
    loss.backward()
    with torch.no_grad():
        w-= .01 * w.grad
        
    w.grad.zero_()    
w   

tensor(2.0000, requires_grad=True)

In [24]:
loss.grad_fn

In [25]:
loss.grad_fn.next_functions[0][0].next_functions[0][0]

# make Neoralnetwork 

i will make data random for X , Y and the neoralnetwork have 2 hidden layers , for the first have 30 unit and second have 16 and the output layer have 10 unit and the activation fun here is Relu 

In [28]:
x = torch.randn((16,1000))
y = torch.randn((16,10))

### make forward class

In [29]:
import torch.nn as nn 

In [47]:
class NeoralNet(nn.Module):
    
    def __init__(self):
        super(NeoralNet , self).__init__()
        
        self.L1 = nn.Linear(1000,30)  # linear here like Dense in Tensorflow 
        self.L2 = nn.Linear(30,16)
        self.L3 = nn.Linear(16,10)
        
        self.relu = nn.ReLU()
        
    def forward(self , x):
        x = self.L1(x)
        x = self.relu(x)
        x = self.L2(x)
        x = self.relu(x)
        x = self.L3(x)
        
        return x 
    

In [48]:
model = NeoralNet()   # like import model from sckit learn 

### Loss function 

In [53]:
Loss = nn.MSELoss()

### optimizer  

In [50]:
import torch.optim as optim 

In [51]:
optimizer = optim.SGD(model.parameters() , lr = 0.01)

leet see the intialziation parameters

In [52]:
model.L2.weight

Parameter containing:
tensor([[ 0.1117, -0.1557,  0.1228, -0.0109, -0.1000,  0.0790, -0.0570,  0.1103,
         -0.0860,  0.0905,  0.0891, -0.0370, -0.0740, -0.1579, -0.1356,  0.1348,
         -0.1376, -0.0195,  0.0218,  0.0714, -0.1075,  0.1010, -0.0824,  0.1309,
          0.1186, -0.1012, -0.0366, -0.0548, -0.0071, -0.0898],
        [-0.0506,  0.1765, -0.0707, -0.1395, -0.0547,  0.1141,  0.1417,  0.1519,
          0.0456, -0.0594, -0.0037,  0.1815, -0.1616,  0.0058, -0.0739,  0.0047,
         -0.0552,  0.1819, -0.0455, -0.0696, -0.0676, -0.0986,  0.0269, -0.0808,
          0.1052,  0.1184, -0.1218, -0.0170,  0.0293, -0.1010],
        [ 0.0245, -0.0611, -0.0009,  0.0696,  0.0558,  0.1441, -0.0950,  0.1322,
         -0.1350,  0.0309,  0.0820,  0.0777,  0.1818,  0.0711, -0.1243,  0.1279,
         -0.0050, -0.0863, -0.0110, -0.0016, -0.1761, -0.0271,  0.1192,  0.0133,
         -0.1582,  0.1654, -0.0797,  0.0835,  0.0603, -0.0693],
        [ 0.0080,  0.0812, -0.0921, -0.1162,  0.0185,  0.

# training loop(backword) 

In [55]:
num_epochs = 1000
for epoch in range(num_epochs):
    optimizer.zero_grad()
    pred = model(x)
    loss = Loss(pred, y)
    loss.backward()
    optimizer.step()
    
    if(epoch+1) % 10 == 0 :
        print(f'epoch[{epoch}]/{num_epochs} , loss= {loss.item():.4f}')

epoch[9]/1000 , loss= 1.0802
epoch[19]/1000 , loss= 1.0336
epoch[29]/1000 , loss= 0.9909
epoch[39]/1000 , loss= 0.9441
epoch[49]/1000 , loss= 0.9008
epoch[59]/1000 , loss= 0.8593
epoch[69]/1000 , loss= 0.8172
epoch[79]/1000 , loss= 0.7751
epoch[89]/1000 , loss= 0.7345
epoch[99]/1000 , loss= 0.6943
epoch[109]/1000 , loss= 0.6556
epoch[119]/1000 , loss= 0.6181
epoch[129]/1000 , loss= 0.5814
epoch[139]/1000 , loss= 0.5445
epoch[149]/1000 , loss= 0.5084
epoch[159]/1000 , loss= 0.4735
epoch[169]/1000 , loss= 0.4405
epoch[179]/1000 , loss= 0.4098
epoch[189]/1000 , loss= 0.3818
epoch[199]/1000 , loss= 0.3565
epoch[209]/1000 , loss= 0.3339
epoch[219]/1000 , loss= 0.3135
epoch[229]/1000 , loss= 0.2953
epoch[239]/1000 , loss= 0.2785
epoch[249]/1000 , loss= 0.2636
epoch[259]/1000 , loss= 0.2504
epoch[269]/1000 , loss= 0.2385
epoch[279]/1000 , loss= 0.2278
epoch[289]/1000 , loss= 0.2178
epoch[299]/1000 , loss= 0.2087
epoch[309]/1000 , loss= 0.2002
epoch[319]/1000 , loss= 0.1923
epoch[329]/1000 , l

In [56]:
model.L2.weight

Parameter containing:
tensor([[ 0.1159, -0.1562,  0.1262, -0.0273, -0.0871,  0.1191, -0.0741,  0.1739,
         -0.0881,  0.0732,  0.0715, -0.0554, -0.0592, -0.1666, -0.1352,  0.1716,
         -0.1339, -0.0190,  0.0106,  0.0960, -0.1469,  0.0921, -0.0821,  0.1303,
          0.1013, -0.1029, -0.0395, -0.0176,  0.0230, -0.0871],
        [-0.0335,  0.2275, -0.1055, -0.1109, -0.0058,  0.2362,  0.2571,  0.2244,
          0.0192, -0.0414, -0.0030,  0.1180, -0.1441,  0.0033, -0.0319,  0.0459,
          0.0189,  0.2290, -0.0380, -0.1189, -0.0546, -0.0875,  0.0777, -0.0833,
          0.1173,  0.1843, -0.1127,  0.0943, -0.0142, -0.1228],
        [ 0.0382, -0.0437,  0.0253,  0.0567,  0.0975,  0.1783, -0.1129,  0.1766,
         -0.1410,  0.0666,  0.0802,  0.0874,  0.2051,  0.0500, -0.0965,  0.1744,
          0.0354, -0.0909, -0.0330, -0.0371, -0.1984, -0.0271,  0.1223,  0.0184,
         -0.1438,  0.2098, -0.0819,  0.1703,  0.1494, -0.0919],
        [-0.0144,  0.0543, -0.0892, -0.1271,  0.0227,  0.

# if i runing the turining loop again it will began from the last weights