In [4]:
import numpy as np

In [5]:
np.ceil(np.sin(np.deg2rad(30)))

1.0

- ceil round for the big

In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.full((3,2),1)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [8]:
np.random.random((3,3))

array([[0.18363215, 0.57451275, 0.3529344 ],
       [0.07033946, 0.34853504, 0.29215097],
       [0.19220683, 0.26409152, 0.81051794]])

In [9]:
c = np.random.randint(0,10,(3,3))
c

array([[6, 7, 0],
       [4, 0, 5],
       [2, 3, 4]])

In [10]:
c[1,2]

5

In [11]:
c[0,:]

array([6, 7, 0])

In [12]:
np.zeros((3,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.eye(3 , dtype = 'int32') # identity matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [15]:
np.diag([1,2,3]) # diagonal matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

<hr>

In [16]:
e = [1,2,3,4,5,6,7,8,9]
np.random.shuffle(e)
e

[6, 8, 5, 3, 4, 2, 7, 9, 1]

In [17]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [18]:
np.any(c>8)

False

In [19]:
np.all(c>8)

False

In [20]:
np.trace(c) # sum of diagonal

10

In [21]:
np.linalg.det(c) # the determainant of the matrix

-131.99999999999997

In [22]:
np.linalg.eig(c) # the adjoient of matrix

(array([10.61863147,  3.22998599, -3.84861745]),
 array([[-0.74601184, -0.66358455,  0.57170297],
        [-0.49222196,  0.26259121, -0.80435483],
        [-0.44853526,  0.70050082,  0.16176843]]))

-  The inverse = adjoient / determainant

<hr>

In [23]:
len(c) # numbers of rows

3

In [24]:
np.size(c) # numbres of the elements

9

In [25]:
c.ndim # dimention of matrix

2

In [26]:
c.shape

(3, 3)

In [27]:
c.dtype

dtype('int32')

In [28]:
d = np.arange(1,11)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.add.accumulate(d) # cumulative

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [30]:
np.multiply.accumulate(d) # factorial of cumulative

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

<hr>

In [31]:
f = np.arange(4).reshape(2,2)
f

array([[0, 1],
       [2, 3]])

In [32]:
g = f*2
g

array([[0, 2],
       [4, 6]])

In [33]:
np.vstack((f,g))

array([[0, 1],
       [2, 3],
       [0, 2],
       [4, 6]])

In [34]:
np.hstack((f,g))

array([[0, 1, 0, 2],
       [2, 3, 4, 6]])

In [35]:
np.max(f)

3

In [36]:
np.argmin(f)

0

In [37]:
f*g   # Every number in the corresponding to him

array([[ 0,  2],
       [ 8, 18]])

In [38]:
np.dot(f,g)

array([[ 4,  6],
       [12, 22]])

# be careful when coping arrays!!!!

In [39]:
a = np.array([1,2,3])
b = a
b[0] = 100
a
# the correct >>> b = a.copy()

array([100,   2,   3])

#              polynomial

In [40]:
poly = np.polynomial.Polynomial
x = np.array([0,20,40,60,80,100,120,140])
y =np.array([10,9,8,7,6,5,4,3])
equation = poly.fit(x,y,1,full=True)
equation

(Polynomial([ 6.5, -3.5], domain=[  0., 140.], window=[-1.,  1.]),
 [array([6.7394794e-30]), 2, array([1., 1.]), 1.7763568394002505e-15])

In [41]:
a = np.poly1d((1,2,3)) # make a equation >>> x2+2x+3
a

poly1d([1, 2, 3])

In [42]:
np.polyder(a) # derivative of equ(a) >> 2x+2

poly1d([2, 2])

In [43]:
np.polyint(a)# intgration

poly1d([0.33333333, 1.        , 3.        , 0.        ])

In [44]:
np.roots(a) # The roots of equ

array([-1.+1.41421356j, -1.-1.41421356j])

In [53]:
a(5)

38

## The End